[project]
name = "roop_custom"
version = "1.0.0"
description = "Take a photo and replace the face in it with a face of your choice. You only need one image of the desired face. No dataset, no training."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy==1.24.3",
    "torch>=2.4",
    "opencv-python==4.8.0.74",
    "onnx==1.14.0",
    "insightface==0.7.3",
    "psutil==5.9.5",
    "tk==0.1.0",
    "customtkinter==5.2.0",
    "pillow==10.0.0",
    "tensorflow>=2.13.0",
    "opennsfw2==0.10.2",
    "protobuf==4.23.4",
    "tqdm==4.66.3",
    "gfpgan==1.3.8",
    "tkinterdnd2==0.3.0; sys_platform != 'darwin' and platform_machine != 'arm64'",
    "tkinterdnd2-universal==1.7.3; sys_platform == 'darwin' and platform_machine == 'arm64'",
    "onnxruntime==1.15.1; python_version != '3.9' and sys_platform == 'darwin' and platform_machine != 'arm64'",
    "onnxruntime-coreml==1.13.1; python_version == '3.9' and sys_platform == 'darwin' and platform_machine != 'arm64'",
    "onnxruntime-silicon==1.13.1; sys_platform == 'darwin' and platform_machine == 'arm64'",
    "onnxruntime-gpu==1.15.1; sys_platform != 'darwin'",
    "typing-extensions>=4.12.2"
]

[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["CodeFormer.basicsr", "roop"]  
exclude = []
namespaces = false

[tool.setuptools_scm]
write_to = "roop_custom/roop/metadata.py"
fallback_version = "1.3.2"
